name: Build Kopia rcbuild artefacts
on:
  push:
    branches:
      - rcbuild

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/ppenguin/xbuildimg/rcbuild-go:arm-glibc2.17-go1.20.1
      env:
        GOOS: linux
        GOARCH: arm
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build arm32v7 binary with make
        uses: actions/run-on-arch-action@v2
        with:
          arch: armv7
          run: make dist/kopia_linux_armv7l/kopia
      - name: Store build artefacts (binary)
        uses: actions/upload-artifact@v3
        with:
          name: dist-binary
          path: |
            dist/kopia_linux_armv7l/kopia
