name: Build Kopia rcbuild artefacts
on:
  push:
    branches:
      - rcbuild

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm
      - name: Run build (under qemu)
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm \
            --platform=linux/arm32v7 \
            -v $(pwd):$(pwd) \
            -w $(pwd) \
            -e GOOS=linux -e GOARCH=arm \
            -e CI=${CI} -e GITHUB_REF=${GITHUB_REF} -e GITHUB_REF_NAME=${GITHUB_REF_NAME} -e GITHUB_REF_TYPE=${GITHUB_REF_TYPE} \
            quay.io/ppenguin/xbuildimg/rcbuild-go:arm-glibc2.17-go1.20.1 \
            make dist/kopia_linux_armv7l/kopia
      # actually run-on-arch action is already a "container-selector"?
      # - name: Build arm32v7 binary with make
      #   uses: uraimo/run-on-arch-action@v2
      #   with:
      #     arch: armv7
      #     run: make dist/kopia_linux_armv7l/kopia
      - name: Store build artefacts (binary)
        uses: actions/upload-artifact@v3
        with:
          name: dist-binary
          path: |
            dist/kopia_linux_armv7l/kopia
